import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col overflow-hidden">
        {/* Navbar at the top */}
        <Navbar />

        <div className="flex flex-1 overflow-hidden">
          {/* Sidebar on the left */}
          <Sidebar />

          {/* Main Content Area */}
          <main className="flex-1 p-5 overflow-auto">
            {children} {/* Page-specific content */}
          </main>
        </div>
      </body>
    </html>
  );
}
